
path: = /Users/tawate/Documents/H2O_Analytics/datasets # absolute path to data
train: imgaes/train  # train images (relative to 'path')
val: imgaes/train # val images (relative to 'path')

# Classes. Include all classes you want to detect
names:
  0: alpaca