path: = /Users/tawate/Documents/H2O_Analytics/computer_vision_learning/Projects/Brain_Tumor_Object_Detection # absolute path to data
train: train/imgs  # train images (relative to 'path')
val: train/imgs # val images (relative to 'path')

# Classes. Include all classes you want to detect
names:
  0: tumor